version: '3.8'

services:
  biosim_web:
    build: .
    ports:
      - "8601:8601"  # Expose Streamlit port
    volumes:
      - .:/app  # Mount current directory for real-time updates
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run BioSimilarity_interface.py --server.port=8601 --server.address=0.0.0.0 --server.maxUploadSize=1000 --server.maxMessageSize=500
